env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:mocha/recommended
  - plugin:node/recommended
overrides:
  - files:
      - test/**/*.js
    rules:
      func-names: off
      prefer-arrow-callback: off
  - files:
      - test/e2e/specs/*
      - test/e2e/pageobjects/*
    rules:
      class-methods-use-this: off

parserOptions:
  ecmaVersion: latest
globals:
  expect: true
  browser: true
  $: true
rules:
  {
    
    "no-unused-vars": ["error", { argsIgnorePattern: "next" }],
    "node/exports-style": ["error", "module.exports"],
    "node/file-extension-in-import": ["error", "always"],
    "node/prefer-global/buffer": ["error", "always"],
    "node/prefer-global/console": ["error", "always"],
    "node/prefer-global/process": ["error", "always"],
    "node/prefer-global/url-search-params": ["error", "always"],
    "node/prefer-global/url": ["error", "always"],
    "node/prefer-promises/dns": "error",
    "node/prefer-promises/fs": "error",
    "node/no-unpublished-require": ["error", { "allowModules": ["supertest"] }]
  }
