name: deploy main

on:
    push:
      branches:
        - main

jobs:
    deploy_main:
        env:
          NODE_ENV: production
          IMAGE: ${{secrets.DEPLOY_CONTAINER}}

        runs-on: ubuntu-latest
        steps:
        - run: "echo now deploying to production"
        - run: "echo Very not-secret image ghcr.io/teresebo/webb22_alm_cicd:sha-${{ github.sha }}"
        - run: "echo Very secret image: $IMAGE"


