name: deploy main

on:
    push:

jobs:
    deploy_main:
        env:
          NODE_ENV: production
          IMAGE: ${{secrets.DEPLOY_CONTAINER}}

        runs-on: ubuntu-latest
        steps:
        - run: "echo now deploying to production"
        - run: "echo Very secret image: $IMAGE"


