name: deploy branch

on:
    push:
      branches-ignore: 
        - main
jobs:
    deploy_branch:
        env:
          NODE_ENV: development
        runs-on: ubuntu-latest
        steps:
        - run: "echo now deploying branch: $GITHUB_REF_NAME to the test server"
        - run: "echo node_env: $NODE_ENV"
        - run: "echo ghcr.io/${{ github.repository }}:${{ github.ref_name }}@${{ github.sha }}"
