name: deploy main

on:
    push:
      branches: 
        - main
jobs:
    deploy_main:
        env:
          NODE_ENV: production

        runs-on: ubuntu-latest
        steps:
        - run: "echo now deploying to production"

