name: deploy branch

on:
    push:
      branches-ignore: 
        - main
jobs:
    deploy_branch:
        runs-on: apline-latest
        steps:
        - run: "echo now deploying branch: $GITHUB_REF_NAME to the test server"
