name: deploy

on:
    push:
      branches-ignore: 
        - main
jobs:
    deploy_main:
        runs-on: ubuntu-latest
        steps:
        - run: "echo now deploying branch: $GITHUB_REF_NAME to the test server"
