
name: 'test_report'
on:
  workflow_run:
    workflows: [testing]                     # runs after testing workflow
    types:
      - completed
env:
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  unit_report:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: unit-test-results            # artifact name
        name: unit-test-results                  # Name of the check run which will be created
        path: unit-test-results.json                     # Path to test results (inside artifact .zip)
        reporter: mocha-json              # Format of test results
        
  integration_report:
        runs-on: ubuntu-latest
        steps:
        - uses: dorny/test-reporter@v1
          with:
           artifact: integ-test-results            # artifact name
           name: Integ Tests                  # Name of the check run which will be created
           path: '*.xml'                     # Path to test results (inside artifact .zip)
           reporter: mocha-json              # Format of test results